services:
  - type: web
    name: n8n
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: PORT
        value: 443
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 72
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: false
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
      - key: EXECUTIONS_MODE
        value: regular
      - key: WEBHOOK_URL
        value: https://api.sophosic.ai
      - key: N8N_HOST
        value: workflows.sophosic.ai
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 443
      - key: N8N_PATH
        value: /
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: N8N_RELEASE_DATE
        value: "2025-03-12T00:00:00Z"
      - key: N8N_WEBHOOK_URL
        value: https://api.sophosic.ai
      - key: N8N_WEBHOOK_TEST_URL
        value: https://api.sophosic.ai
      - key: N8N_EDITOR_BASE_URL
        value: https://workflows.sophosic.ai
      - key: N8N_EDITOR_BASE_API_URL
        value: https://api.sophosic.ai
      - key: N8N_FRONTEND_DOMAIN_URL
        value: https://workflows.sophosic.ai
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: free
